version: "3.7"
services:
  db:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - '${VOLUME_FOLDER:-.volumes}/db:/var/lib/mysql'
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3305}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-amazing_gud_read_development}
      MYSQL_USER: ${DB_USERNAME:-itnihongo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}

